// Auto-generated by make — do not edit
let buildVersion = "1.8.0"
let buildCommit = "c1508b7"
let buildBranch = "feature/agentic-vectors"
let buildDate = "2026-06-06 19:30:59 UTC"
let buildSwiftVersion = "6.3.1"
let buildOS = "macOS 26.4.1"
