// Auto-generated by make — do not edit
let buildVersion = "1.8.0"
let buildCommit = "134d933"
let buildBranch = "main"
let buildDate = "2026-06-01 11:20:22 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
