// Auto-generated by make — do not edit
let buildVersion = "1.7.0"
let buildCommit = "b54dfca"
let buildBranch = "main"
let buildDate = "2026-05-20 14:13:42 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
